### ISSUE TITLE
Support null-safety

### ISSUE THREAD

**Issue by isorensen** [felixlucien/flutter-autocomplete-textfield#111]
Hello! thanks for the awesome package.

Dart 2.12 and flutter 2.0.0 are now in stable with the null-safety feature.

Migrating this package to null-safety would help a lot. :)

Here's an official guide from dart doc
https://dart.dev/null-safety/migration-guide

**Comment by leynier** [comment]
Any update about this guys? I could help with this.

**Comment by Zeswen** [comment]
Waiting for this to update our application to Flutter 2.0!

It would be awesome to have it ASAP. Thank you for your great work :)

**Comment by Zeswen** [comment]
@leynier @isorensen This projects has no updates since 2 years ago.

I suggest to make a fork of it and try to make it ourselves!

**Comment by Zeswen** [comment]
Here is [my take](https://github.com/Zeswen/flutter-autocomplete-textfield) on null-safety with this package!

In case you don't know how to add my fork to your project, here is an example of `pubspec.yaml`:

```yaml
name: ...
description: ...
version: 1.0.0
author: Zeswen
homepage: ...

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  autocomplete_textfield:
    git: https://github.com/Zeswen/flutter-autocomplete-textfield
```
